apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Namespace omitted: Argo CD sets it ("cuffney-com").
labels:
  - pairs:
      app.kubernetes.io/part-of: cuffney-com
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - ingress-internal.yaml
configMapGenerator:
  - name: cuffney-com-nginx
    files:
      - default.conf=nginx.conf
